### ISSUE TITLE
English

### ISSUE THREAD

**Issue by sushank1** [OtakuZhangyk/the_crew2-DR-#1]
Can u help me run this? or make an English version of this?

**Comment by sunilgknair051** [comment]
I can make a rough version of it into English, but needs more work later on. Assign if interested. Thanks!

**Comment by sushank1** [comment]
Yes please make an English version. Thank you very much.

**Comment by sunilgknair051** [comment]
@sushank1, I have created a English version and requested a PR. If you have write access, please review and merge.
Would be helpful!
Thanks.

**Comment by sushank1** [comment]
I don't have write access and the original poster isn't active for quite
some time, eould you mind sharing here?

**Comment by sunilgknair051** [comment]
@sushank1, I would mind (sorry!). If it gets merged, it would help both of us. And @OtakuZhangyk hasn't responded as of yet.

**Comment by sushank1** [comment]
Did you make an english version of the readme file or the script?

**Comment by sunilgknair051** [comment]
I have added translations on both.
